### ISSUE TITLE
What does this plugin actually do?

### ISSUE THREAD

**Issue by gotofritz** [roman-r-m/joplin-plugin-table-formatter#11]
This is one of the recommended plugins, yet I have no idea what this does. There are no instructions, no screenshots, nothing.

From trial and error I discovered that it turns this

```
| asdasd | asdasd |
|----------|-----------|
| asdasd | asdasd |
```

into this

```
| asdasd | asdasd |
|--------|--------|
| asdasd | asdasd |
```

But it would be nice if it said so somewhere

**Comment by executed** [comment]
yeah def needs to be added to README.md
