### ISSUE TITLE
Add "Format Table" to context menu

### ISSUE THREAD

**Issue by okoetter** [roman-r-m/joplin-plugin-table-formatter#7]
At the moment you'll need to invoke this plugin via the Edit menu. Is it possible to add this menu entry to the context menu? So when I right click on a table to select "Format Table" here?

**Comment by roman-r-m** [comment]
Yes, that makes sense, I'll add it. However I don't think it is possible to only show the menu entry when you click inside a table.

**Comment by roman-r-m** [comment]
Fixed in 1.2.0
